server:
  port : 8080

spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/microservice1/**
          filters:
            - StripPrefix=0
            - name: Hystrix
              args:
               name: microservice1
               fallbackUri: forward:/fallback
          uri: "http://localhost:8081"

        - predicates:
            - Path=/microservice2/**
          filters:
            - StripPrefix=0
            - name: Hystrix
              args:
                name: microservice2
                fallbackUri: forward:/fallback
          uri: "http://localhost:8082"


hystrix.command.microservice1.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.microservice2.execution.isolation.thread.timeoutInMilliseconds: 5000